# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='description',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
